# Generated by Django 3.2.4 on 2021-07-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productQuantity', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
